### ISSUE TITLE
is it possible to add ansible forms as a tab in awx ui

### ISSUE THREAD

**Issue by nx2804** [ansibleguy76/ansibleforms#102]
Hi 

I wanted to check the feasibility of adding ansible forms tab in awx ui like inventories, credentials,job templates

**Comment by ansibleguy76** [comment]
I don't understand the question entirely.

I do have the feeling you want the operator to have full control of all inventories, credentials, etc... that's not really what AF was built for.  it was built to have RBAC and to have control over what operators can do.  That was what was missing from AWX.  

But you can always query AWX and have dropdown boxes with templates, credentials, inventories and then target AWX with your selections.  

AF is a great addition on top of AWX.

**Comment by nx2804** [comment]
no no i am trying to consolidate both the UI's . so that is it possible to have a single one , that is the reason i was checking for this

**Comment by ansibleguy76** [comment]
no plans for that.
