### ISSUE TITLE
LDAP Authentication does not work

### ISSUE THREAD

**Issue by Puntjuh** [ansibleguy76/ansibleforms#103]
Hi,

I've been attempting to configure LDAP with AnsibleForms (version 4.0.16, runs in Debian 11), which runs in Docker but so far no luck.
The configuration when tested works, but logging in throws this error message: 

> 2023-10-11 11:45:48:4548 notice: Certificates are valid
> 2023-10-11 11:45:48:4548 notice: Checking ldap connection ok
> 2023-10-11 11:46:34:4634 info: Checking password for user admin.dimitri
> 2023-10-11 11:46:34:4634 info: [ansibleforms] running query : SELECT users.id,`username`,`password`,GROUP_CONCAT(groups.name) `groups` FROM AnsibleForms.`users`,AnsibleForms.`groups` WHERE `users`.group_id=`groups`.id AND username=?;
> 2023-10-11 11:46:34:4634 debug: [ansibleforms] query result : [{"id":null,"username":null,"password":null,"groups":null}]
> 2023-10-11 11:46:34:4634 info: [ansibleforms] running query : SELECT * FROM AnsibleForms.`ldap` limit 1;
> 2023-10-11 11:46:34:4634 debug: [ansibleforms] query result : [{"server":"x.x.x.x","port":389,"ignore_certs":1,"enable_tls":0,"cert":"","ca_bundle":"","bind_user_dn":"CN=Ansible Forms,OU=Service Accounts,OU=xxxx,DC=xxx,DC=NL","bind_user_pw":"xxxx","search_base":"OU=Administrators,OU=x,DC=x,DC=NL","username_attribute":"sAMAccountName","enable":1}]
> 2023-10-11 11:46:34:4634 info: Checking ldap for user admin.dimitri
> 2023-10-11 11:46:34:4634 error: Error connecting to ldap : user not found or usernameAttribute is wrong

I've tried to enlarge the search base by removing either one or both OU to no avail. 

Regards,

Dimitri

**Comment by ansibleguy76** [comment]
the “connection test” is not a 100% guarantee.  it is a connection test and
not a search test.  the error “user not found” means the connection works
but user can’t be found.  you might need permissions on the ou where the
users are.

Op wo 11 okt 2023 om 13:53 schreef Puntjuh ***@***.***>

**Comment by Puntjuh** [comment]
Thanks, i had a typo, which i've overlooked a 100 times unfortunately. apologies.
