### ISSUE TITLE
AzureAD integration retrieves only first 100 groups

### ISSUE THREAD

**Issue by dariopai** [ansibleguy76/ansibleforms#105]
**Describe the bug**
AzureAD integration retrieves only first 100 groups during the login process. 
See /client/src/views/Login.vue#L78
...
axios.get(`${this.azureGraphUrl}/v1.0/me/transitiveMemberOf`,config)
...

**To Reproduce**
1.Login using AzuerAd but having assigned +than 100 groups

**Expected behavior**
To have a custom filter of groups on displayName or to be able to manage +100 groups jumping on multiple pages and retrieve them all. See APi doc at > https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http#skiptoken-parameter

**Screenshots**
n/a

**Version**
ansibleforms v4.0.10

**Deployment**
Deployed ansibleforms with :
-  kubernetes

**Additional context**
n/a

**Comment by ansibleguy76** [comment]
code has been modified.  4.0.17 is in beta.  i was not able to test myself.  if you are in the possibility to test this?  
the change is to recursively get the next page @odata.nextLink.

**Comment by dariopai** [comment]
yes, I can test it but as I'm running it from inside k8s I'd need to know the procedure to overwrite the fixed files inside the pod.

**Comment by ansibleguy76** [comment]
should be fixed in 4.0.17

**Comment by ansibleguy76** [comment]
4.0.17 release

**Comment by dariopai** [comment]
I've downloaded and tested v4.0.18 from docker-hub and it seems it works oks now. I see +100 groups populated inside "about me". Good for you!

**Comment by ansibleguy76** [comment]
Do note that you might encounter another issue with this, which I already had on another customer.
The accesstoken, holding all the groups (needed for RBAC), was getting to big for their nginx.  Header too large.
In azureAD you can set a filter to reduce the number of groups returned.

**Comment by dariopai** [comment]
hi, for some users using AzureAD the login process is now returning "COULD NOT GET YAML FILE / AXIOSERROR: REQUEST FAILED WITH STATUS CODE 400".

I dont see any error in log file:

kubectl -n ansibleformsNS logs -f server-55765f5847-mfl6z
...
2023-11-13 09:04:34:434 debug: Login
2023-11-13 09:04:35:435 info: Loading /app/dist/persistent/forms.yaml
2023-11-13 09:04:35:435 debug: validating forms.yaml against schema
2023-11-13 09:04:35:435 debug: Valid forms.yaml
2023-11-13 09:04:35:435 debug: {"username":"firstname.lastaname@company.com","id":"14f3affc-c10a-4cff-918c-XXXXXXXXX","type":"azuread","groups":["azuread/group1","azuread/group2","azuread/group3","azuread/group4"...,"azuread/group250"],"roles":["public"]}
2023-11-13 09:04:35:435 info: Storing refreshtoken in database for user firstname.lastaname@company.com
2023-11-13 09:04:35:435 info: Adding token for firstname.lastaname@company.com.com (azuread)
2023-11-13 09:04:35:435 info: [ansibleforms] running query : INSERT INTO AnsibleForms.`tokens` set ?
2023-11-13 09:04:35:435 debug: [ansibleforms] query result : {"fieldCount":0,"affectedRows":1,"insertId":0,"info":"","serverStatus":2,"warningStatus":0,"changedRows":0}
...

**Comment by ansibleguy76** [comment]
After upgrade, you should definitely refresh the browser CTRL-F5.  Caching the previous version can cause issues.  
This also doesn't seem related to the authentication.  If CTRL-F5 does not fix it, can you make a new issue.
I would also advise to limit the group using a filter in AzureAD, the accesstoken could become too big to be passed as a header.  Because all the groups are stored in the token for RBAC.

**Comment by dariopai** [comment]
control+F5 didnt solve the problem, now I'm testing with a non default max-header in nginx and it seems to work!


nginx.conf / default value for server section => large_client_header_buffers 4 8k;
..........
it works now with this new settings => large_client_header_buffers 8 16k;

**Comment by ansibleguy76** [comment]
Just a FYI.  Version 4.0.19 now has an AzureAD group filter, which allows you to add a regex and limit the grouplist.
