### ISSUE TITLE
New Feature - Storing playbooks in a GIT repository

### ISSUE THREAD

**Issue by revolonl** [ansibleguy76/ansibleforms#108]
No issue only a way to store ansible playbook in GIT repository. 
**Describe the solution you'd like**

I would like to store all my playbooks in a GIT.
It would permit to have a simple code modification tracking.
 Then in the form, i could specify the yaml file in the GIT repo directly.
If i am right,this feature exist in AWX.

**Comment by ansibleguy76** [comment]
i will close this
