### ISSUE TITLE
LDAP - AD group based configuration

### ISSUE THREAD

**Issue by jakszk** [ansibleguy76/ansibleforms#11]
Hello,

Due to some unknown issue, I cannot set the LDAP auth properly. When I configure it to use username attribute: sAMAccountName, it looks like the connection is fine (message: LDAP connection ok) but when I look at logs, I can see such entries:
2022-01-20 15:07:56:756 info: Certificates are valid
2022-01-20 15:07:56:756 info: Checking ldap connection result : user not found or usernameAttribute is wrong
2022-01-20 15:07:56:756 debug: user not found or usernameAttribute is wrong

When I try to login with LDAP, it shows the same message: user not found or usernameAttribute is wrong.
All in all, it is not possible to use it, is there any more extensive docs showing all allowed in ansible forms LDAP attributes? Is it possible to use it with AD groups or simple ldap servers only?

Thanks for help :)

**Comment by ansibleguy76** [comment]
how are you logging in.  you should not add the domain. just the user.  the connection test actually even tries to connect with a dummy user and i even rely on the message unknown user as i then know the connection is valid.  i have only tested this with AD.  perhaps we can setup a teams meeting and have a look together.  also the search base must be correct.
