### ISSUE TITLE
AWX |  AWX "Workflow Job Template" launch failed

### ISSUE THREAD

**Issue by ronrem** [ansibleguy76/ansibleforms#117]
Hi,

I would like to extend my gratitude for the excellent application you have developed, and I appreciate the ongoing efforts to maintain its quality.

I am writing to inform you that I have successfully integrated Ansibleforms with our AWX environment, allowing me to create forms and launch AWX "Job Templates" seamlessly. At this juncture, I am eager to advance my form capabilities and simulate a "Workflow Job Template, by stitching multiple node and passing through artifacts."

AWX Workflow Job Template Integration: I have been unable to initiate an AWX "Workflow Job Template" directly from Ansibleforms. Could you please clarify if this is by design, and if so, could you provide instructions or insights into the reasoning behind this limitation, and maybe some workarounds?

I appreciate your time and assistance in addressing these inquiries.

Thank you once again for your exceptional work, and I look forward to your prompt response.

Best Regards,
Ronald

**Comment by ansibleguy76** [comment]
Hi, yes workflow job templates should work.  If a job template is not found, it will retry and search for a workblow template.
Do you get a specific error ?  What version are you running ?

Can you repost your second questions, so we can keep question threads separately ?

**Comment by ansibleguy76** [comment]
Let me try it

**Comment by ronrem** [comment]
> I have the same error... let me check whats wrong

Thanks for your confirmation.

**Comment by ansibleguy76** [comment]
found and fixed the issue, will be fixed in v4.0.20

**Comment by ansibleguy76** [comment]
1) make sure you don't have surveys => then block extravars
2) make sure you have "prompt" on for the properties you try to pass. (inventory, extravars, ...)

**Comment by ronrem** [comment]
Awesome !! I can confirm that it is working now.
