### ISSUE TITLE
Ldap config not retrieving groups/username

### ISSUE THREAD

**Issue by MalfuncEddie** [ansibleguy76/ansibleforms#119]
**Describe the bug**
Can login with ldap user (open-ldap) but unable to retrieve username/groups. (the about me is empty)

I tried to replicate my awx ldap config this to ansible forms but I am a bit stuck on it.  I think the user search and group search are needed but you cannot configure this?

for the record my awx "redacted" ldap config:

LDAP User Search
```
[
  "DC=xxx,DC=yyy",
  "SCOPE_SUBTREE",
  "(uid=%(user)s)"
]
```
LDAP Group Search
```
[
  "OU=zzz,DC=xxx,DC=yyy",
  "SCOPE_SUBTREE",
  "(objectClass=groupOfNames)"
]
```
LDAP User Attribute Map
```
{
  "email": "mail",
  "first_name": "givenName",
  "last_name": "sn"
}
```
LDAP Group Type Parameters
```
{
  "name_attr": "uid"
}
```

**To Reproduce**
have an open ldap config
configure ldap like in the documentation

**Expected behavior**
I am logged in with correct username and groups in the "about me"
<img width="757" alt="image" src="https://github.com/ansibleguy76/ansibleforms/assets/1717515/02c445dc-0f01-46ae-ab31-2b734e44395b">

**Version**
ansibleforms v4.0.19

**Deployment**
Deployed ansibleforms with :
- using ansibleforms-dockercompose

**Additional context**
```
2023-12-03 20:33:27:3327 info: [ansibleforms] running query : SELECT enable,groupfilter FROM AnsibleForms.`azuread` limit 1;
2023-12-03 20:33:36:3336 info: Checking password for user a_scsn
2023-12-03 20:33:36:3336 info: [ansibleforms] running query : SELECT users.id,`username`,`password`,GROUP_CONCAT(groups.name) `groups` FROM AnsibleForms.`users`,AnsibleForms.`groups` WHERE `users`.group_id=`groups`.id AND username=?;
2023-12-03 20:33:36:3336 info: [ansibleforms] running query : SELECT * FROM AnsibleForms.`ldap` limit 1;
2023-12-03 20:33:36:3336 info: use tls : true
2023-12-03 20:33:36:3336 info: reject invalid certificates : false
2023-12-03 20:33:36:3336 info: Checking ldap for user XXXXX
2023-12-03 20:33:42:3342 info: Loading /app/dist/persistent/forms.yaml
2023-12-03 20:33:42:3342 info: merging file maintenance.yaml
2023-12-03 20:33:42:3342 info: Loading /app/dist/persistent/forms.yaml
2023-12-03 20:33:42:3342 info: merging file maintenance.yaml
2023-12-03 20:33:42:3342 info: ldap login for undefined
2023-12-03 20:33:42:3342 info: Storing refreshtoken in database for user undefined
2023-12-03 20:33:42:3342 info: Adding token for undefined (ldap)
2023-12-03 20:33:42:3342 info: [ansibleforms] running query : INSERT INTO AnsibleForms.`tokens` set ?
2023-12-03 20:33:42:3342 error: [ansibleforms] Query error : Error: Column 'username' cannot be null
2023-12-03 20:33:42:3342 error: An uncaught exception happened in db.model.js.  Column 'username' cannot be null
2023-12-03 20:33:42:3342 info: [ansibleforms] running query : SELECT approval FROM AnsibleForms.`jobs` WHERE status='approve' AND approval IS NOT NULL;
2023-12-03 20:33:42:3342 info: Loading /app/dist/persistent/forms.yaml
2023-12-03 20:33:42:3342 info: merging file maintenance.yaml
2023-12-03 20:35:39:3539 info: Finding all jobs
2023-12-03 20:35:39:3539 info: [ansibleforms] running query : SELECT id,form,target,status,start,end,user,user_type,job_type,parent_id,approval FROM AnsibleForms.`jobs` WHERE (user=? AND user_type=?) OR (status='approve') ORDER BY id DESC LIMIT 500;
2023-12-03 20:35:39:3539 info: [ansibleforms] running query : SELECT approval FROM AnsibleForms.`jobs` WHERE status='approve' AND approval IS NOT NULL;
```

**Comment by ansibleguy76** [comment]
hi,
i have never tested against openldap since i didn't have one.  can we connect privately to debug this together?  i will
probably need
to deploy an openldap.

**Comment by MalfuncEddie** [comment]
Hi,

Unfortunately I am mistaken. I thought it was open ldap but it is something different (forgerock). 
I'm going to setup a dev environment and try to see if I can alter the user model. It's been a long time since I used ldapsearch so give me some time ;)

**Comment by MalfuncEddie** [comment]
https://github.com/ansibleguy76/ansibleforms/blob/9b1dd130f86d137f085a9f582522ee60486380a1/server/src/auth/auth_basic.js#L47C1-L47C50

should that not be ldap.username_attribute instead of result.sAMAccountName -> since you can config this in the ldap settings?

still no groups but looking further

**Comment by ansibleguy76** [comment]
beta is pushed, set your docker image to :beta (instead of :latest) and retest, the correct attribute will be used.

**Comment by MalfuncEddie** [comment]
Username is solved in beta, 

Still debugging the group issue, the npm ldap package looks like it can do it but currently no success :-(

**Comment by MalfuncEddie** [comment]
I believe this is a bug in ldap-authentication. Given the same options ldap search to ldap-authentication give [null] as groups and ldapsearch retuns a result. Will continue to debug and if needed open a issue there.

**Comment by ansibleguy76** [comment]
Wait a second, groups are actually grabbed by my code.

```
    if(groupObj.memberOf){
      // get the memberOf field, force to array
      var ldapgroups = [].concat(groupObj.memberOf)
      //logger.debug(`LDAP Groups = ${ldapgroups}`)
      // loop ldap groups
      ldapgroups.forEach(function(v,i,a){
        // grab groupname part
        var groupMatch=v.match("^[cCnN]{2}=([^,]*)")
        if(groupMatch.length>0){
          // prefix with ldap
          group="ldap/" + groupMatch[1]
          // add all the roles that match the group
          groups.push(group)
        }
      })
    }
    return groups
```
and my assumtion here is that the "`memberOf`" property holds the groups and that they are in the format of `CN=...`
Can I make a beta that writes the result to the logs so we can debug the object returned ?  We might have to grab another property.

**Comment by ansibleguy76** [comment]
a new beta is pushed which will write (debug level) the entire ldap object.

```
2023-12-05 20:56:46:5646 debug: Ldap object :
2023-12-05 20:56:46:5646 debug: {"dn":"CN=Administrator,CN=Users,DC=slash,DC=local","objectClass":["top","person","organizationalPerson","user"],"cn":"Administrator","description":"Built-in account for administering the computer/domain","distinguishedName":"CN=Administrator,CN=Users,DC=slash,DC=local","instanceType":"4","whenCreated":"20170914101704.0Z","whenChanged":"20231204201746.0Z","uSNCreated":"8196","memberOf":["CN=test,OU=Test,DC=slash,DC=local","CN=Group Policy Creator Owners,CN=Users,DC=slash,DC=local","CN=Domain Admins,CN=Users,DC=slash,DC=local","CN=Enterprise Admins,CN=Users,DC=slash,DC=local","CN=Schema Admins,CN=Users,DC=slash,DC=local","CN=Administrators,CN=Builtin,DC=slash,DC=local"],"uSNChanged":"62874415","name":"Administrator","objectGUID":"\u0003ַ�y�)H����Lpj","userAccountControl":"66048","badPwdCount":"0","codePage":"0","countryCode":"0","badPasswordTime":"133462834052809510","lastLogoff":"0","lastLogon":"133462834064060229","logonHours":"���������������������","pwdLastSet":"131535721969932441","primaryGroupID":"513","objectSid":"\u0001\u0005\u0000\u0000\u0000\u0000\u0000\u0005\u0015\u0000\u0000\u0000\u0011�k*�Eˤ,�\t�\u0001\u0000\u0000","adminCount":"1","accountExpires":"0","logonCount":"65535","sAMAccountName":"Administrator","sAMAccountType":"805306368","objectCategory":"CN=Person,CN=Schema,CN=Configuration,DC=slash,DC=local","isCriticalSystemObject":"TRUE","dSCorePropagationData":["20170914103258.0Z","20170914103258.0Z","20170914101748.0Z","16010101181216.0Z"],"lastLogonTimestamp":"133461946667709773","msDS-SupportedEncryptionTypes":"0"}
```
Can you test and post your result ?

**Comment by MalfuncEddie** [comment]
Hi,

I also edited user.model.js so I could add groupsSearchBase,groupClass,groupMemberAttribute,groupMemberUserAttribute

```
User.checkLdap = function (username, password) {

  return Ldap.find()
    .then((ldapConfig) => {
      if (ldapConfig.enable == 1) {
        return ldapConfig
      } else {
        throw "No ldap configured or not enabled"
      }
    })
    .then(async (ldapConfig) => {
      // auth with admin
      var badCertificates = false
      let options = {
        ldapOpts: {
          url: ((ldapConfig.enable_tls == 1) ? "ldaps" : "ldap") + "://" + ldapConfig.server + ":" + ldapConfig.port,
          tlsOptions: {}
        },
        adminDn: ldapConfig.bind_user_dn,
        adminPassword: ldapConfig.bind_user_pw,
        userPassword: password,
        userSearchBase: ldapConfig.search_base,
        usernameAttribute: ldapConfig.username_attribute,
        username: username,
        groupsSearchBase: "censored",
        groupClass: 'groupOfNames',
        groupMemberAttribute: 'memberUid',
        groupMemberUserAttribute: 'uid'


        // starttls: false
      }
```
When dumping the object I get
```
{
  "dn": "censored",
  "objectClass": [
    "shadowAccount",
    "posixAccount",
    "top",
    "organizationalPerson",
    "person",
    "inetOrgPerson"
  ],
  ....
  "gidNumber": "54321",
  "uidNumber": "12345",
  "uid": "xxx",
  "groups": [null ]
}
```


Also when I use a user with multiple groups it is  "groups": [null, null ]


Also logged a ticket here since I am 95% convinces it is an ldap-authentication bug
https://github.com/shaozi/ldap-authentication/issues/59

**Comment by ansibleguy76** [comment]
now now. hacking the code.  have i found my first contributor? 😊

**Comment by MalfuncEddie** [comment]
perhaps, but i'm a total noob in the javascript eco system. I just keep editing and googling till it works .

**Comment by ansibleguy76** [comment]
Isn't it "groupSearchBase" instead of groupsSearchBase (s too many)

**Comment by ansibleguy76** [comment]
Anyhow, I'll have to allow a lot more option-properties as it seems.  I'll make a checkbox "advanced".

**Comment by MalfuncEddie** [comment]
> Isn't it "groupSearchBase" instead of groupsSearchBase (s too many)

It looks ok if I read the docs of ldap-authentication

>Anyhow, I'll have to allow a lot more option-properties as it seems. I'll make a checkbox "advanced".

tnx :) I'll keep debugging and will keep it updated :)

**Comment by ansibleguy76** [comment]
I believe the documentation is wrong and there is an "s" too many.

**Comment by MalfuncEddie** [comment]
this works for me : added the elsif ins user.model.js

```
  if (user.type == "ldap") {
    if (groupObj.memberOf) {
      // get the memberOf field, force to array
      var ldapgroups = [].concat(groupObj.memberOf)
      logger.info(`LDAP Groups = ${ldapgroups}`)
      // loop ldap groups
      ldapgroups.forEach(function (v, i, a) {
        // grab groupname part
        var groupMatch = v.match("^[cCnN]{2}=([^,]*)")
        if (groupMatch.length > 0) {
          // prefix with ldap
          group = "ldap/" + groupMatch[1]
          // add all the roles that match the group
          groups.push(group)
        }
      })
    }
    else if (groupObj.groups) {
      var ldapgroups = [].concat(groupObj.groups)

      ldapgroups.forEach(function (v, i, a) {
        var groupMatch = v.objectName.match("^[cCnN]{2}=([^,]*)")
        logger.info(JSON.stringify(groupMatch, null, 2))
        group = "ldap/" + groupMatch[1]
        groups.push(group)
      })
    }
```

**Comment by ansibleguy76** [comment]
> this works for me : added the elsif ins user.model.js
> 
> ```
>   if (user.type == "ldap") {
>     if (groupObj.memberOf) {
>       // get the memberOf field, force to array
>       var ldapgroups = [].concat(groupObj.memberOf)
>       logger.info(`LDAP Groups = ${ldapgroups}`)
>       // loop ldap groups
>       ldapgroups.forEach(function (v, i, a) {
>         // grab groupname part
>         var groupMatch = v.match("^[cCnN]{2}=([^,]*)")
>         if (groupMatch.length > 0) {
>           // prefix with ldap
>           group = "ldap/" + groupMatch[1]
>           // add all the roles that match the group
>           groups.push(group)
>         }
>       })
>     }
>     else if (groupObj.groups) {
>       var ldapgroups = [].concat(groupObj.groups)
> 
>       ldapgroups.forEach(function (v, i, a) {
>         var groupMatch = v.objectName.match("^[cCnN]{2}=([^,]*)")
>         logger.info(JSON.stringify(groupMatch, null, 2))
>         group = "ldap/" + groupMatch[1]
>         groups.push(group)
>       })
>     }
> ```

so if I would add a groupsattribute that can be changed (like memberOf, groups), the code would work ?  But it still required the the other options (groupsSearchBase, ...)

**Comment by MalfuncEddie** [comment]
yes

```
        groupsSearchBase: "censored",
        groupClass: 'groupOfNames',
        groupMemberAttribute: 'memberUid',
        groupMemberUserAttribute: 'uid'
```
still has to be added an configured in the gui and a configurable groupsattribute  (like memberOf, groups), should solve the issue an probably other exotic ldap configs :)

**Comment by ansibleguy76** [comment]
will push a beta later tonight

**Comment by ansibleguy76** [comment]
pushing beta now... try in 10 minutes (don't forget to do ctrl-f5 to refresh browser).
the groups attributes will be memberOf by default, change it to "groups", check "is advanced" and fill the rest.
For now, you will see a debug logging in the logs of the ldap options, I'll remove this after debug is pushed.
let me know the result.

**Comment by MalfuncEddie** [comment]
Yeah so ldap-authentication need to release the next version before these changes.

If you would like I could test these changes and manually insert the main branch of ldap authentication. That way you know if the fix works.

**Comment by MalfuncEddie** [comment]
> I don't understand, I use v3.0.3 and that has the pojo change.

I also don't understand it. I asked it on the issue 

https://github.com/shaozi/ldap-authentication/issues/56#issuecomment-1846721189

the fix is in line 151

and on npm it shows object instead of pojo
https://www.npmjs.com/package/ldap-authentication/v/3.0.3?activeTab=code


I also checked the beta container

```
/app/node_modules/ldap-authentication # grep -n object  index.js
4:// convert a SearchResultEntry object in ldapjs 3.0
5:// to a user object to maintain backward compatibility
9:  let user = { dn: pojo.objectName }
72:// search a user and return the object
140:        filter: `(&(objectclass=${groupClass})(${groupMemberAttribute}=${user[groupMemberUserAttribute]}))`,
151:          groups.push(entry.object)
/app/node_modules/ldap-authentication #
```

I do not understand why a group fix from 3 moths ago doe not trigger a 3.0.4 release.

**Comment by MalfuncEddie** [comment]
I just checked out the beta ( and some docker foo to get the latest version of ldap-authentication

I got no groups


I fixed it by adding ["objectName"]
https://github.com/ansibleguy76/ansibleforms/blob/1e4235125b4163fd28e7a20dffefdbd0b0699354/server/src/models/user.model.js#L163
```
// grab groupname part
        var groupMatch=v["objectName"].match("^[cCnN]{2}=([^,]*)")
        if(groupMatch.length>0){

```

I cant remember if this was also needed 1 moth ago 

Also Happy NY

**Comment by ansibleguy76** [comment]
Can you hack a console.log(v) in there ?  So I can see the entire object ?
In AD, adding the objectName breaks it.

**Comment by MalfuncEddie** [comment]
here it is,( please remember I am using the master github version of ldap-authentication


`logger.debug(v)`

 13:44:57:4457 debug: [object Object]

`logger.debug(JSON.stringify(v))`
 
output anonymized
```
debug:{
   "messageId":2,
   "protocolOp":100,
   "type":"SearchResultEntry",
   "objectName":"CN=blah,OU=bumba,OU=Groups,OU=Samson,DC=plop,DC=piet",
   "attributes":[
      {
         "type":"objectClass",
         "values":[
            "top",
            "posixGroup",
            "groupOfNames"
         ]
      },
      {
         "type":"gidNumber",
         "values":[
            "920213225"
         ]
      },
      {
         "type":"cn",
         "values":[
            "blah"
         ]
      },
      {
         "type":"memberUid",
         "values":[
            "bumba",
            "bumbalu"
         ]
      },
      {
         "type":"member",
         "values":[
            "CN=Bumba,OU=bumba,OU=Groups,OU=Samson,DC=plop,DC=piet",
            "CN=Bumbalu,OU=bumba,OU=Groups,OU=Samson,DC=plop,DC=piet"
         ]
      }
   ],
   "controls":[
      
   ]
}

```

**Comment by ansibleguy76** [comment]
```
2024-01-07 16:18:18:1818 debug: "CN=test,OU=Test,DC=slash,DC=local"
2024-01-07 16:18:18:1818 debug: "CN=Group Policy Creator Owners,CN=Users,DC=slash,DC=local"
2024-01-07 16:18:18:1818 debug: "CN=Domain Admins,CN=Users,DC=slash,DC=local"
2024-01-07 16:18:18:1818 debug: "CN=Enterprise Admins,CN=Users,DC=slash,DC=local"
2024-01-07 16:18:18:1818 debug: "CN=Schema Admins,CN=Users,DC=slash,DC=local"
2024-01-07 16:18:18:1818 debug: "CN=Administrators,CN=Builtin,DC=slash,DC=local"
```
This is my output and I have implemented that latest main (just copy-pasted the code, no npm), so that means AD and your return is quite different.

I will first try "objectName" and then fall back, but I just wonder how many ldap server flavours there are and how different they all are.

**Comment by ansibleguy76** [comment]
building new beta now... finished in 5 minutes.  Please give it a spin ?

**Comment by ansibleguy76** [comment]
just for the logs, what flavour of ldap server are you using ?

**Comment by MalfuncEddie** [comment]
forgerock openam

**Comment by MalfuncEddie** [comment]
> building new beta now... finished in 5 minutes. Please give it a spin ?

Everything works!

**Comment by ansibleguy76** [comment]
my pleasure stefan.  shall we close it?

**Comment by MalfuncEddie** [comment]
> my pleasure stefan. shall we close it?

yes
