### ISSUE TITLE
Proxy http https Environment Variables

### ISSUE THREAD

**Issue by abedk** [ansibleguy76/ansibleforms#123]
Hi  ansibleguy76,

Thank you for this very nice software!

Would be helpful to have http_proxy https_proxy and no_proxy   for people behind web proxies.

Also would be fab if we can edit these from https://localhost:8443/#/settings  directly

Many thanks for considering

**Comment by ansibleguy76** [comment]
can't you simply do that with env vars?

HTTPS_PROXY

**Comment by abedk** [comment]
Yes exactly using env vars. I assumed you used this page for env var editing? See image attached
![Uploading Screenshot 2023-12-09 at 3.32.51 pm.png…]()

**Comment by ansibleguy76** [comment]
env vars must be set outside.  in configmaps or in the dockercompose file.
