### ISSUE TITLE
Allow options for publishing log files and downloading it from UI

### ISSUE THREAD

**Issue by nx2804** [ansibleguy76/ansibleforms#135]
Hi Team,

I have a set of containers running on my k8 clusters. All the logs which are generated by application is being mounted to hostpath under certain directory. I wanted to publish those logs to ui can you please enable the feature

Thanks

**Comment by ansibleguy76** [comment]
Hi, can you first explain in details what it is you request.  You want to publish logs in the gui, that doesn't explain a lot.
But expect this to be a no-fix.
