### ISSUE TITLE
SSH expression returning 2 extra values - "" and "exit(0)"

### ISSUE THREAD

**Issue by checkifexist** [ansibleguy76/ansibleforms#138]
**Describe the bug**
I am using enum field, and in expression I am get ls from remote ssh, its returning all file correctly, but 2 fields are extra - one is blank and other is exit(0). Also can we filter these through jq-expression, if yes, can anyone tell how?

**To Reproduce**

Create below form label
- name: list 
    type: enum 
    expression: fn.fnSsh('<username>','<ipaddress>','ls /home/files/')

**Expected behavior**
enum dropdown containing only file that are actually present
for eg - in my case files v1, v2.... v5 were present in that directory
but it shows 2 extra selectable field empty and exit(0)
**Screenshots**
![image](https://github.com/ansibleguy76/ansibleforms/assets/157472645/899dc895-aa1d-4118-a851-455484eb048c)
on clicking eye button below json is shown
![image](https://github.com/ansibleguy76/ansibleforms/assets/157472645/344de870-cdf6-4433-9549-136085dbbea5)

**Version**
ansibleforms:latest

**Deployment**
Deployed ansibleforms with :-
 using ansibleforms-dockercompose

**Additional context**
You can ask for more info

**Comment by checkifexist** [comment]
Updates: I have explicitly disabled to show last two rows, using jq-expression. Its working fine
Used jq-expression : `fn.fnSsh('<username>','<ipaddress>','ls` /home/files/','.[:-2]')`

**Comment by ansibleguy76** [comment]
This is by design. It is not necessarily returning an array. this is by design. It is not necessarily returning an array. it is simply returning the output, followed with the exit code. It is up to you to parse the content parse the exit code, and drop it if needed.
