### ISSUE TITLE
Add user email to users (local and ldap) and ansibleforms_user

### ISSUE THREAD

**Issue by MalfuncEddie** [ansibleguy76/ansibleforms#147]
**Is your feature request related to a problem? Please describe.**
It would be nice if the user object can be expanded with an email field.
In awx you can use the tower_user_email variable to send mails to the user that launched the template. When using ansible forms this no longer works since this is mapped to a single AWX user.

**Describe the solution you'd like**
add the field email to the user model and if it is ldap map a certain ldap field tot the mail field in the user model

```
"ansibleforms_user": {
    "username": "username",
    "type": "ldap",
    "email": "email@email.com" <- this
    "groups": [
      "ldap/group"
    ],
    "roles": [
      "public",
      "operator"
    ]
  },
```

**Describe alternatives you've considered**
using the rest api to query the users of AWX and if a user matches add the email to the extra_vars

**Additional context**

**Comment by ansibleguy76** [comment]
```

"ansibleforms_user":
{
"username":
"kürt",
"email":
"kurt.baes@netapp.com",
"type":
"ldap",
"groups":
[
],
"roles":
[
"public"
]
},
```

will be in 5.0.1 (ldap only) => after update, you need to set the mail attribute in ldap to "mail"

**Comment by ansibleguy76** [comment]
building 5.0.1 beta now

**Comment by MalfuncEddie** [comment]
> building 5.0.1 beta now

tested and works!
