### ISSUE TITLE
 JQ filtering issue results to " " instead of boolean(false)

### ISSUE THREAD

**Issue by nikos445** [ansibleguy76/ansibleforms#155]
Ansible Form JQ filtering always results to " " (empty string) when the result of JQ filtering is a boolean and results in **false**

e.g.
Example: 
-->   { data: [ false, false, false, false ] }

filtering with jq  -->     **.data | any(. == true)**       --> will result in  "" if false and true if there is any true inside the data array.

**Comment by nikos445** [comment]
![IMG_20240221_144806](https://github.com/ansibleguy76/ansibleforms/assets/3193713/4a59dbe9-b65e-41d0-a614-27eb87844403)
Take a look on result here...
This jq returns an array with false as example above.

**Comment by nikos445** [comment]
adding filter like -->  **.data | any(. == true)  | tostring**  will result to "false" but its not boolean.

**Comment by ansibleguy76** [comment]
fixed in 5.0.1
