### ISSUE TITLE
Global cross form constants repository 

### ISSUE THREAD

**Issue by hmarko75** [ansibleguy76/ansibleforms#17]
Having a global place to keep constants can be very nice. 
You can limit those to static values to prevent too much complexity. 

YAML implementation can be: 

categories:
 .. 
roles: 
 ... 
constants:
 str1: 'yoyo'
 int1: 32

those could be accessed from expressions like this: 

expression: $(const.str1)+' koko'

**Comment by ansibleguy76** [comment]
if you stay in 1 yaml file, you can actually just use anchors.  Basic functionality of yaml.
but this will break in the multiple yaml files.

**Comment by ansibleguy76** [comment]
Added new constants section in forms.yaml.
Use as key-value like 
```
SERVERX: 172.16.0.1
SERVERY: 172.16.0.2
```
