### ISSUE TITLE
Return `extravars` & `credentials` as a JSON object not a JSON string

### ISSUE THREAD

**Issue by dsha256** [ansibleguy76/ansibleforms#171]
Currently `extravars` & `credentials` are returned as a JSON string. Returning them as JSON objects would be great.

Currently:
```str
"extravars": "{\"name\":\"vm1\",\"region\":\"myregion\",\"opco\":\"myopco\"}"
```

After:
```json
{
  "name": "vm1",
  "opco": "myopco",
  "region": "myregion"
}
```

**Comment by ansibleguy76** [comment]
Hi, I'm not entirely sure what you mean.  The goals of AF is to send extravars to either AWX or local ansible.  They are sent in the correct format.  It's the receiving end that needs to parse the json.  But maybe I understand your question wrong.

**Comment by dsha256** [comment]
I mean the the formats of the values (`extravars` & `credentials`) in the response body given in the screenshot. IDK, maybe that was meant to be shown like it is now for some reason. 
![image](https://github.com/ansibleguy76/ansibleforms/assets/56347073/6d1a4f01-2318-47e4-8128-3b072abf4064)

**Comment by ansibleguy76** [comment]
aha.. I understand.  I could indeed make that an object.  I just hope that won't break for others then.  Same for credentials then.

**Comment by ansibleguy76** [comment]
will be fixed in 5.0.2 (beta coming today).  changed together with credentials, approvals, substeps, notifications.  All now converted in objects in the api call.  The client code is changed too where it is now no longer parsed.

**Comment by ansibleguy76** [comment]
new beta is now being pushed.  use image ":beta" instead of ":latest".  And use ctrl-F5 to clear the browser cache.
let me know the outcome

**Comment by ansibleguy76** [comment]
I will close this... ping me if you think it should not be closed
