### ISSUE TITLE
SQL Query error

### ISSUE THREAD

**Issue by dsha256** [ansibleguy76/ansibleforms#172]
I'm trying to update an already louched job through the API endpoint `https://localhost:8443/api/v1/job/116`.  I get 200 OK in Postman 
![image](https://github.com/ansibleguy76/ansibleforms/assets/56347073/bad352cc-3ff7-41a2-933d-6962edfa2f4f)

But, it's not updating actually. This is an error from the docker-compose logs:
```txt
af_app  | 2024-05-04 11:43:22:4322 error: Failed to update job You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id='119'' at line 1
```

**Comment by ansibleguy76** [comment]
that's an illegal post action and is not documented in the docs.  i am shocked though, it got allowed...
It's not part of the routes, very strange.

**Comment by ansibleguy76** [comment]
I have just tried this and I cannot do that api action.
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /api/v1/job/451</pre>
</body>
</html>

**Comment by ansibleguy76** [comment]
ah, I see it's a put

**Comment by ansibleguy76** [comment]
it is meant for status changes, and is more an internal api.  And I even wonder if it's used.  I believe it is not and can be removed.

It does work on my end, but it's not meant to send extravars etc...
![image](https://github.com/ansibleguy76/ansibleforms/assets/89778474/4c9fa909-0dfe-4301-bf39-1f1cdebc9697)

![image](https://github.com/ansibleguy76/ansibleforms/assets/89778474/55996c1b-b860-43c4-98fc-b470bce13698)

**Comment by dsha256** [comment]
> I have just tried this and I cannot do that api action.
> 
> <title>Error</title>
> Cannot POST /api/v1/job/451

I did that via the HTTP UPDATE

**Comment by dsha256** [comment]
> it is meant for status changes, and is more an internal api. And I even wonder if it's used. I believe it is not and can be removed.
> 
> It does work on my end, but it's not meant to send extravars etc... ![image](https://private-user-images.githubusercontent.com/89778474/327954611-4c9fa909-0dfe-4301-bf39-1f1cdebc9697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MzMwMzksIm5iZiI6MTcxNDgzMjczOSwicGF0aCI6Ii84OTc3ODQ3NC8zMjc5NTQ2MTEtNGM5ZmE5MDktMGRmZS00MzAxLWJmMzktMWYxY2RlYmM5Njk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE0MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjkwMDA1MWZjM2M3NjEwNjhmMTNmNzhlZTNhNGE1MjI2ZGIxNjgyMTczNWMyZjgzNTA4ZWE2MTllY2ZmNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ct1jOW5qexT5ojqa_5LNG6K7VPbbD7U0h__6cnd9WGQ)
> 
> ![image](https://private-user-images.githubusercontent.com/89778474/327954713-55996c1b-b860-43c4-98fc-b470bce13698.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MzMwMzksIm5iZiI6MTcxNDgzMjczOSwicGF0aCI6Ii84OTc3ODQ3NC8zMjc5NTQ3MTMtNTU5OTZjMWItYjg2MC00M2M0LTk4ZmMtYjQ3MGJjZTEzNjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE0MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NTgzMWZmMmY1MGVhYzc5Yzg2N2NlZDc5OTNkNDY2MmMyZTdmYWVmMDYyYTM3NWVkMDQ4Zjc3MjI5ZTUwMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-6zE3RZJ7XfnXspWaKumPVvxVn7tckMwDa8zMf4qTxg)

So by design, I'm not allowed to PUT or PATCH a job as a API user right?

**Comment by ansibleguy76** [comment]
correct.  you launch a job and then abort/relaunch/delete, but you can't change it;  Only internal code changes the job (status, timestamps, output, etc...)

**Comment by ansibleguy76** [comment]
I just double checked and the put is not used.  I will remove it in the next version.
