### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by shubhammer** [ansibleguy76/ansibleforms#2]
Can we add an option to run the playbooks in check mode from forms , this will be helpful for validating the playbooks and forms in production environment.

**Comment by hmarko75** [comment]
As a temp solution, you can get the ansible-playbook cmd from the ansibleforms.log. it will show you the full command including args which you can tweak

cat ansibleforms.log | grep ansible-playbook

**Comment by ansibleguy76** [comment]
check & diff properties are added as form properties.
You can also trigger check & diff using a boolean-result field (checkbox or expression)
the fields should be name \_\_check\_\_ and \_\_diff\_\_
