### ISSUE TITLE
ERROR! the playbook: dummy.yaml could not be found 2024-08-11 16:33:28 [ERROR]: Playbook failed with status (1) 2024-08-11 16:33:28

### ISSUE THREAD

**Issue by birb57** [ansibleguy76/ansibleforms#200]
Hello

one more issue from my side

when trying to run demo form/job I got below error 👍 
ERROR! the playbook: dummy.yaml could not be found 2024-08-11 16:33:28
[ERROR]: Playbook failed with status (1) 2024-08-11 16:33:28

N.B: Very easy installation

Thanks for your support

**Comment by birb57** [comment]
running job is  Demo Form Ansible No input

**Comment by vcmirko** [comment]
it only works if you also used the docker-compose project.  That one has the dummy.yaml.
I just deployed a new instance and the dummy works fine
