### ISSUE TITLE
Cant add SSH Key

### ISSUE THREAD

**Issue by tovoro** [ansibleguy76/ansibleforms#216]
Whatever I try, I cannot add a private key under Settings -> SSH 
I always get a "Invalid Form Data" Error and I found nothing in the documentation.

![CleanShot 2024-09-05 at 17 06 50@2x](https://github.com/user-attachments/assets/be234709-a0c9-4d21-a742-09278047b943)

What am I doing wrong? 

Im running the latest Docker Build with Docker-Compose on a Debian 11 Host.

**Comment by ansibleguy76** [comment]
Hmmm, weird.  I use the regex ^-----BEGIN (.+) PRIVATE KEY-----([^-!]+)-----END \1 PRIVATE KEY-----\r?\n$
And the regex should work fine.  But I have it too.

I'll have to file it as a bug.
For now, you can simple go in the container, if you are allowed and goto /root/.ssh/  => you can set the proper files there manually.  PS : first run will generate a private key. 

![image](https://github.com/user-attachments/assets/86851026-931e-4ca5-94ad-9bdde15d6d08)

**Comment by tovoro** [comment]
Thanks for your answer, the regex looks wrong to me, this  works: 

^-----BEGIN ([A-Z ]+ PRIVATE KEY)-----\r?\n([^-]+)\r?\n-----END \1-----$

**Comment by ansibleguy76** [comment]
if you test it in regexr, the regex works fine.  And the new line was required.

**Comment by ansibleguy76** [comment]
![image](https://github.com/user-attachments/assets/02ae84e6-6378-4567-b6f4-c4399c17c18c)

`^-----BEGIN ([A-Z ]+ PRIVATE KEY)-----\r?\n([^-]+)\r?\n-----END \1-----\r?\n$`

**Comment by tovoro** [comment]
Doesnt work on [regex101](https://regex101.com) tester
![CleanShot 2024-09-06 at 09 36 03@2x](https://github.com/user-attachments/assets/1d330678-b8d8-4004-a9c7-3388812fc071)

**Comment by ansibleguy76** [comment]
because I require the new line

**Comment by ansibleguy76** [comment]
I'll spin up a dev version, change the regex and see if it works.
Potentially I could add the new line in code.

**Comment by ansibleguy76** [comment]
I'm building a beta image now.  Can you test it and see if your regex fixes it ?
Can you certainly do a ctrl-F5 in the browser so that the client app is refreshed.  ETA image  = 10min

**Comment by ansibleguy76** [comment]
now in 5.0.5 latest
