### ISSUE TITLE
After the upgrade from v4.0.19 to v5.0.4 the authentication with AzureAD stopped working for some users

### ISSUE THREAD

**Issue by dariopai** [ansibleguy76/ansibleforms#228]
**Describe the bug**
After the upgrade from v4.0.19 to v5.0.4 the authentication with AzureAD stopped working for some users. The web-error for these users says "Identity Provider Login failed, no token found" and at the pod's console the error says  "error: invalid algorithm  .. error: Failed to obtain access token". It seems it has some relation with the length of the token since for those who are able to login the size of the callback url seems to be shorter (not 100% secure). AF is running as 2 pods inside a k8s cluster and using mysql 8.1.

**To Reproduce**
Login with AzureAD

**Expected behavior**
Same users using v4 could login using AzureAD in the same server with no errors.

**Version**
ansibleforms v5.0.4 (pod images inside a k8s v 1.29.x)

**Deployment**
Deployed ansibleforms with :
- kubernetes 1.29.x

**Screenshots**

Error when login with AzureAD
![image](https://github.com/user-attachments/assets/f7168505-8570-4812-86ef-709e889f3582)

Error at pod's console:
![image](https://github.com/user-attachments/assets/af0bb705-fcf2-4c2b-b880-de3a89bad12a)
....
2024-09-25 12:15:14:1514 debug: Schema check from cache     
2024-09-25 12:15:17:1517 debug: Redirect to azure           
2024-09-25 12:15:19:1519 debug: Schema check from cache     
2024-09-25 12:15:20:1520 debug: Login                       
2024-09-25 12:15:20:1520 error: invalid algorithm           
2024-09-25 12:17:02:172 error: Failed to obtain access token
...

Browsing when error pression F2 at edge:
![image](https://github.com/user-attachments/assets/9c239209-8af2-4736-8ea9-1052348155fd)

Browsing when user is able to access ok with AzureAD credentials:
![error_afv504_and_msentraid_browsing003_OK](https://github.com/user-attachments/assets/87c9d464-6527-4230-ac48-18f414bc9755)

**Comment by ansibleguy76** [comment]
I assume duplicate with 229

**Comment by ansibleguy76** [comment]
I've had it once before that someone has so many groups that my own token is too long, but would not explain the behavior after the upgrade.  That why I built in a filter for the groupnames.

**Comment by ansibleguy76** [comment]
I went through the code.. nothing really changed on the authentication;  Can you verify the ones where it fails, have done a browser refresh ctrl-f5 ?  If they have an old cached client version, you can have strange things

**Comment by ansibleguy76** [comment]
can you please verify the cache refresh. if the old client connects to the new backend, unexpected things can happen.

**Comment by dariopai** [comment]
cleaning up browser's cache did not solve the issue, sorry ... even the /api/v1/auth/azureAD/login redirect page in V4 was changed to /api/v1/auth/oidc/login in V5 .. is that correct???


![image](https://github.com/user-attachments/assets/cd92b5b3-958b-4592-922f-aadd9f016e15)

**Comment by ansibleguy76** [comment]
that doesnt make any sense.  i would have several reports about this. i have several deployments where azure ad is working fine.  i cant simulate this.  oidc is the op id connector.  has its own table.  can you check the database?  what records are in tables azuread and oidc?

**Comment by dariopai** [comment]
![image](https://github.com/user-attachments/assets/61624c9f-df01-422a-b39d-074c4387b8e1)

**Comment by dariopai** [comment]
![image](https://github.com/user-attachments/assets/f753990e-0b78-416f-835a-ae75c8221bda)

**Comment by dariopai** [comment]
reviewing the code at Login.vue it seems that in line 42 the logic is getting "oidc" instead of "azuerad" ... so the token from azuread is not being processed in the right way

![image](https://github.com/user-attachments/assets/bd9b33b0-b1a1-43b4-bea3-704236b74bb0)

**Comment by ansibleguy76** [comment]
thank you for the feedback. i will review asap!   regarding the groups.  would it mean the group regex is not applied?

**Comment by ansibleguy76** [comment]
Found the bug !  I will fix now and make a new release !

**Comment by ansibleguy76** [comment]
i only happened if I get a "next tag"

**Comment by ansibleguy76** [comment]
this also means that >100 groups (using the next tag) is hitting the same bug

**Comment by ansibleguy76** [comment]
a new beta is pushed.  image tag beta (ansibleguy/ansibleforms:beta)

**Comment by ansibleguy76** [comment]
if you could do me favour and test it ?

**Comment by dariopai** [comment]
i could if you create the image to upload to my K8s

**Comment by ansibleguy76** [comment]
image on docker hub. tag beta

**Comment by ansibleguy76** [comment]
fixed in new release 5.0.7
