### ISSUE TITLE
Openshift Deployment - scheme and tables are not ok

### ISSUE THREAD

**Issue by keys1234249** [ansibleguy76/ansibleforms#230]
**Describe the bug**
After deployment of fresh AnsibleForms the pods are created and running as expected however it appears that the DB schema is created but not the tables needed for the app to function.

**To Reproduce**
Deploy K8 example to openshift cluster

**Expected behavior**
App to load properly

**Screenshots**
![image](https://github.com/user-attachments/assets/baa53460-e1d9-4b2f-9fe5-c0e60c164b12)

**Version**
ansibleforms v5.0.6

**Deployment**
Deployed ansibleforms with :
- kubernetes (OpenShift 4.16)

**Additional context**
[server-76d4984df7-wjt9s-server.log](https://github.com/user-attachments/files/17236426/server-76d4984df7-wjt9s-server.log)

**Comment by ansibleguy76** [comment]
do you have logs of both containers?  the right permissions are present?

what is the value of the environment
variable ALLOW_SCHEMA_CREATION.

**Comment by ansibleguy76** [comment]
can you surf to /#/install ?
that should bring you to an install status overview. 

/#/schema should allow you to create the database.  unless you have the env var allow_schema_creation on 0.

**Comment by keys1234249** [comment]
Hello when i navigate to /#/install i get this:
![image](https://github.com/user-attachments/assets/210ff7c7-a9ae-4981-945c-31916001ee2a)

mysql pod logs:
[mysql-6fbfb4d9cc-m7h9n-mysql.log](https://github.com/user-attachments/files/17243954/mysql-6fbfb4d9cc-m7h9n-mysql.log)

When i navigate to /#/schema i get the original screenshot shown in my first post. When you mention are the permissions correct what are you referring to?

As for the variable ALLOW_SCHEMA_CREATION i have set this to "1" within the ansibleforms-env configmap.

`data:
  ALLOW_SCHEMA_CREATION: '1'
  LOG_CONSOLE_LEVEL: debug
  LOG_LEVEL: debug
  MYSQL_DATABASE: AnsibleForms
  NODE_ENV: production
`

**Comment by ansibleguy76** [comment]
the database install has not run completely.  permission on disk?  permissions of the user?  is this a new db server or existing?

can you remove the databas ansibleforms and restart the application pod?  it should prompt you with the ask to recreate.

**Comment by keys1234249** [comment]
Good idea, i dropped the DB and reloaded the app. It prompted me to create the DB/schema and i can login now. Thanks!
