### ISSUE TITLE
 Connection error : Error: getaddrinfo EAI_AGAIN mysqldbE

### ISSUE THREAD

**Issue by nx2804** [ansibleguy76/ansibleforms#232]
When i try to setup ansible forms using docker flow. It fails with following error Kindly suggest on this please
<img width="761" alt="image" src="https://github.com/user-attachments/assets/e5f173f9-a24e-4210-9530-0d4be3a883e5">

**Comment by nx2804** [comment]
<img width="797" alt="image" src="https://github.com/user-attachments/assets/d32b29b9-6a12-486d-bc12-5bc2b8f3adaf">

**Comment by ansibleguy76** [comment]
can it be that the ip network from docker (often 172.x.x.x) is interfering with your host network?  also make sure the dns is working in the container. there is this dns option15 to enable dns passthrough

**Comment by ansibleguy76** [comment]
Maybe I should consider a 10 second delay

**Comment by ansibleguy76** [comment]
and a few retries

**Comment by ansibleguy76** [comment]
found the issue.  Building new **beta**.  Application should now correctly wait for mysql to become ready.

**Comment by ansibleguy76** [comment]
fixed in new beta... (building now, ready in 10 minutes) please test. new release will follow soon.

**Comment by ansibleguy76** [comment]
fixed in new release 5.0.7
