### ISSUE TITLE
Unable to update awx url in Ansibleforms 

### ISSUE THREAD

**Issue by nx2804** [ansibleguy76/ansibleforms#233]
updating awx url is always failing with invalid form data error

<img width="885" alt="image" src="https://github.com/user-attachments/assets/24062733-614c-479d-be4c-429ce39b4e18">

but when i try to test the connection it works fine kindly suggest
<img width="919" alt="image" src="https://github.com/user-attachments/assets/b4fc60d4-81a2-4420-a7a7-048b67b1ae95">

**Comment by ansibleguy76** [comment]
are you running the latest?  i believe this was fixed.  but i will double check asap

**Comment by nx2804** [comment]
yes i am using the latest one from main branch

**Comment by ansibleguy76** [comment]
Did this happen after an upgrade? And if so, did you refresh the browser cash?

**Comment by nx2804** [comment]
Unfortunately this is not logging any error message in logs to troubleshoot

**Comment by ansibleguy76** [comment]
what version does the help say?

**Comment by nx2804** [comment]
V5.0.6

**Comment by ansibleguy76** [comment]
ok. will verify.

**Comment by nx2804** [comment]
Sure I observed one more thing this functionality works find with v5.0.4 image

**Comment by ansibleguy76** [comment]
5.0.6 got a form validation update.  i will check right away

**Comment by ansibleguy76** [comment]
found it and fixed it.  Latest version had new vuelidate package which worked slightly different.  New beta is building.  if you have the capability to update to ansibleguy/ansibleforms:beta / do ctrl-F5 and then test again ?

**Comment by ansibleguy76** [comment]
fixed in new release 5.0.7
