### ISSUE TITLE
File Upload Feature together with AWX Job

### ISSUE THREAD

**Issue by janhoelscher** [ansibleguy76/ansibleforms#236]
** What i want to do?** 

I want to Upload a File via a File Field, imagine for example .csv and use it inside my AWX Job. 

** Question **
Is there a simple way? 
I first thought, that i can download the file from my ansibleforms instance by an HTTP Request in my AWX Job, but this gets an Error. But it could maybe an Option to allow this URL to specific IPs (in this Case the AWX Worker).

**Comment by ansibleguy76** [comment]
there is a file field. 
it will upload a file to a temp location and in the extravars the details will be injected with original name, temp name.  in your playbook you can move the file as you please.  see ansibleforms.com and check out the file field type.

**Comment by janhoelscher** [comment]
Yes, i agree that this works for an local ansible job on the Ansibleform host.

But i want to access this in my AWX Job. 

There Happens only the Rest Call to start the Job, but no copy.

Is there a way to access this file?
Or maybe is this an feature request to make uploaded files remotly accessable?

**Comment by ansibleguy76** [comment]
you sure the copy isn't happening. 
it should.  you could then have the location set on some shared drive with an http server for example.  and thus awx could reach it over http. 

let me know.

**Comment by ansibleguy76** [comment]
closing this, due to inactivity and no response
