### ISSUE TITLE
set boundaries for number fields 

### ISSUE THREAD

**Issue by hmarko75** [ansibleguy76/ansibleforms#27]
Hi. 

I have a use case with 2 number inputs. i want to validate the 2nd number field will be higher than the 1st (soft and hard quota limits) 

currently, the minVaule and maxVaule are static. It will be great to have those dynamically evaluated based on variables.

**Comment by ansibleguy76** [comment]
in next release I will add an expression based validation.  this will allow all the freedom you desire.

**Comment by hmarko75** [comment]
Hi 

Please also include it in when I'm using the number field within the table field. 

I will also need clarification on how to use it correctly cause this doesn't seem towork: 

    - type: number
      name: field2
      label: field2
      default: ""
      required: false
      minValue: 0
      maxValue: 2100000000
      icon: user
      regex:
        expression: ^[0-9]*$
        description: Invalid number   
       validIf:
         field: ($(field2)>=$(field1))
         description: field2 should be bigger or equal field1

**Comment by ansibleguy76** [comment]
Use another expression field to make the validation
Like 
```
- name: isBigger
  type: expression
  expression: ($(field2)>=$(field1))
- name: field2
  type: number
  isValidIf: isBigger
```
