### ISSUE TITLE
Complex column output in query from list of dict

### ISSUE THREAD

**Issue by Ryan1edm** [ansibleguy76/ansibleforms#28]
When collecting information from a rest API call, is there a way to display the contents of an [ object Object ] from the results.

Specific example is previewing the client match list from the rules index of an export policy on a netapp.

- name: rules
    type: query
    expression: fn.fnRestBasic('get','https://$(netapp.ip)/api/protocols/nfs/export-policies/$(exportpolicyid)/rules?return_records=true&return_timeout=15&fields=clients','','ontapcred','[.records[]]')
    label: Display of rules
    columns:
      - index
      - clients    <<<< this does not show the content of the match list.   It shows [object Object] in the table dropdown like this.

The output from the call returns the following fields.  The index display properly on the dropdown table, but I am trying to show the Match list on the form .  mostly for information at this time, but allows the user to see the content of the rule.

"index":1,
"clients":[
    {
         "match": "192.168.1.0/24"
     }
]

**Comment by ansibleguy76** [comment]
Let's make it more complete 
```
{
	"records": [{
			"index": 1,
			"clients": [{
				"match": "192.168.1.0/24"
			}]
		},
		{
			"index": 2,
			"clients": [{
					"match": "192.168.2.0/24"
				},
				{
					"match": "192.168.3.0/24"
				}
			]
		}
	]
}
```
that's the input.

Now use jqplay.org
`[.records[] | {"index": .index, "clients": .clients[].match}]`

the output is now :
```
[
  {
    "index": 1,
    "clients": "192.168.1.0/24"
  },
  {
    "index": 2,
    "clients": "192.168.2.0/24"
  },
  {
    "index": 2,
    "clients": "192.168.3.0/24"
  }
]
```
this flattens the list, takes out the part 'match' but you will now have a record per match.

**Comment by Ryan1edm** [comment]
Ah, didn't think to flatten the records.   thanks.  that should do it.     Great example too, can you add that to the wiki ?

**Comment by Ryan1edm** [comment]
Updated expression produces forms warning errror

This:
expression: fn.fnRestBasic('get','https://$(netapp.ip)/api/protocols/nfs/export-policies/$(exportpolicyid)/rules?return_records=true&return_timeout=15&fields=clients','','credentials','[.records[] | {"index": .index, "clients": .clients[].match}]')

Produces error:  YAMLSemanticError: Nested mappings are not allowed in compact mappings

Current version is 2.2.2 installed.  Updated to 2.2.3 and same error.

**Comment by ansibleguy76** [comment]
can you first show the output without the filtering ?
Do you get results from your rest api ?

**Comment by ansibleguy76** [comment]
this is a yaml issue in your forms.yaml.

best way to test yaml error is on [yamllint.](http://www.yamllint.com/)
just copy past everything in there and validate for errors

**Comment by Ryan1edm** [comment]
Thanks.  This is probably a pebkac issue on my end.   appreciate the response and help.

**Comment by ansibleguy76** [comment]
no worries.  the issue of often een | pipe character or something, which is a yaml character, then you need to explicitely say it's a string by wrapping the lot in quotes.

**Comment by ansibleguy76** [comment]
As soon as I have time I will start my blog and have more example there.
