### ISSUE TITLE
AWX dynamic inventory

### ISSUE THREAD

**Issue by jakszk** [ansibleguy76/ansibleforms#29]
**Is your feature request related to a problem? Please describe.**
At the moment it is only possible to use already existing AWX inventory - when you create a form you need to know its name.
Therefore you cannot easily generate the inventory and execute an AWX playbook against it.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Ideally it would be great to have some function/custom field which could create a temporary AWX inventory (with a given name) before launching the playbook, then put hosts from any given either string or flat array there, execute the playbook against that inventory and afterwards remove. Could be used as a checkbox which you can tick to decide whether such inventory should be used or not.

**Comment by ansibleguy76** [comment]
Version 3.0.0 now has a multistep action allow you to create a pre & post task in ansible/awx.
