### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by shubhammer** [ansibleguy76/ansibleforms#3]
Is this possible if we add use of queries in table columns.

**Comment by ansibleguy76** [comment]
This is now possible in `2.1.7beta`+
Use tablefield-type `query` + propery `from`.
the `from` property must point to an `expression` on the form that has the loaded data.

**Comment by ansibleguy76** [comment]
ps : all typical columns are available
- valueColumn
- previewColumn
- filterColumns (+new in 2.1.7)
- columns
- outputObject => will add the full object in the tablefield !
