### ISSUE TITLE
Syslog Integration

### ISSUE THREAD

**Issue by matthew-beattie** [ansibleguy76/ansibleforms#34]
**Syslog integration**
The functionality to send the logs to a syslog server would be a useful security feature.

**Current alternatives to syslog**
Configure AnsibleForms as a proxy to AWX and use that to forward logs to the syslog server

**Additional context**
Enterprise infrastructures typically utilize syslog for centralized log storage. Enabling AnsibleForms to support syslog forwarding would be a useful security improvement.

**Comment by ansibleguy76** [comment]
Any specific features ?  Or just syslog-host is sufficient.

- host: The host running syslogd, defaults to localhost.
- port: The port on the host that syslog is running on, defaults to syslogd's default port.
- protocol: The network protocol to log over (e.g. tcp4, udp4, tls4, unix, unix-connect, etc), defaults to udp4.
- protocolOptions: Socket connect options. See [net.socket.connect](https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener) for available options.
- path: The path to the syslog dgram socket (i.e. /dev/log or /var/run/syslog for OS X).
- pid: PID of the process that log messages are coming from (Default process.pid).
- facility: Syslog facility to use (Default: local0).
- localhost: Host to indicate that log messages are coming from (Default: localhost).
- type: The type of the syslog protocol to use (Default: BSD, also valid: '3164', '5424', 'RFC3164' or 'RFC5424').
- app_name: The name of the application (Default: process.title).
- eol: The end of line character to be added to the end of the message (Default: Message without modifications).

**Comment by ansibleguy76** [comment]
3.0.1 is out in beta...
