### ISSUE TITLE
rerun form 

### ISSUE THREAD

**Issue by hmarko75** [ansibleguy76/ansibleforms#35]
Hi.

Please consider to add the ability to rerun failed/completed forms from the job history view.

**Comment by ansibleguy76** [comment]
it would be (to be clear) like this :
- recording the forms basic info 
   - formname
   - type
   - playbook/template/repo/steps
   - inventory, tags, check, diff
- create new job with the previous extravars

**Comment by hmarko** [comment]
Yes. This can be usefull for rerenung failed jobs after solving the issue.
Equivelnt api will be usefull as well.

**Comment by ansibleguy76** [comment]
this has be implemented in 3.0.1 (in beta for now)
