### ISSUE TITLE
provide alternative to functions/default.js and locate it in the persistent folder

### ISSUE THREAD

**Issue by hmarko75** [ansibleguy76/ansibleforms#4]
Hi.

To keep all modified files within a single location and prevent a change of built-in function file need to provide a location for something like custom-functions.js and locate it somewhere within the persistent directory to enable ease editing and source control.

**Comment by ansibleguy76** [comment]
under /app/dist/src/functions there is now a custom.js
The functions exported are accessible using `fnc.` 2 sample functions are added.
