### ISSUE TITLE
Limit AWX execution to single host

### ISSUE THREAD

**Issue by robschm** [ansibleguy76/ansibleforms#41]
I'm trying to limit the execution of my playbook to a single host, which originates from a query.
I couldn't find any hint in the documentation on how to set the limit value.

**Comment by ansibleguy76** [comment]
You should use ansible inventories for that.
[https://github.com/ansibleguy76/ansibleforms/wiki/1.-Forms.yaml-file#inventory](https://github.com/ansibleguy76/ansibleforms/wiki/1.-Forms.yaml-file#inventory)

**Comment by hmarko75** [comment]
You can see an example here on how I implemented it using the hosts key:

https://github.com/hmarko75/ansibleforms_service_catalog/blob/master/data/playbooks/dataops_create_clone.yaml

**Comment by ansibleguy76** [comment]
is this clear now ?

**Comment by ansibleguy76** [comment]
I'll close this due to inactivity... feel free to reopen if you need more help

**Comment by ansibleguy76** [comment]
Thank you Ewan to point this out.  
Version 4.0.3 will have the limit option for both ansible & awx.  It will also be controlable with the __limit__ field.

**Comment by ansibleguy76** [comment]
Version 4.0.3 is public.  limit is now a valid property
