### ISSUE TITLE
add colon (:) to the table search + remove older search strings when query entries dynamically updated 

### ISSUE THREAD

**Issue by hmarko75** [ansibleguy76/ansibleforms#42]
Hi

if possible please include the ability to search by a colon (:) in a query field.

plus. 

Currently, the previous search is preserved even after the entries have been updated due to dependency change. 
if possible to reset the search only when entries are updated in the query due to dependency change it can be great.

**Comment by ansibleguy76** [comment]
can you split this up in 2 issues ?  In this I'll only handle the search colon part.

That being said : I can't simulate this.  It works fine on my end, I can filter on any character.

**Comment by ansibleguy76** [comment]
rewrote this in new beta 3.0.2, please test is you can

**Comment by hmarko75** [comment]
the colon works for me too but I can swear it didn't work last time I checked it

**Comment by ansibleguy76** [comment]
in the new beta, the search has become an actual input field
