### ISSUE TITLE
retrieve user logged in

### ISSUE THREAD

**Issue by dblazquezl** [ansibleguy76/ansibleforms#49]
**Is your feature request related to a problem? Please describe.**
In AWX I can use the awx_user internal variable to retrieve the user logged in the GUI
Is there any option to use any ansibleforms internal variable to retrieve the user logged?

**Describe the solution you'd like**
I would like a similar approach, some kind of internal variable I can map to a awx variable 

Sorry if this is already solved, I looked into the docs and closed issues and couldn't find it
thanks!

**Comment by ansibleguy76** [comment]
Hi,

Good question.  No it's not in there yet...  But I was about to make a new fix release.  
Would ansibleforms_user be a good fit ?  Would you also like additional information ?  An object perhaps :

ansibleforms_user
   name: admin
   type: ldap
   group: admins

**Comment by dblazquezl** [comment]
Hi, yes the object would be great, specially the group attribute!!

Thanks a lot!

**Comment by dblazquezl** [comment]
Amazing!! Thanks!
