### ISSUE TITLE
AWX connection - unable to get local issuer certificate

### ISSUE THREAD

**Issue by jakszk** [ansibleguy76/ansibleforms#5]
When I try to make the connection to my instance of AWX, it throws the following error: _unable to get local issuer certificate._
The server deployment logs throw exactly the same thing.
AWX url and token I used should be fully valid - checked on another application.
Please support in solving the issue.

**Comment by ansibleguy76** [comment]
what version are you using.  this is solved in the latest version.

**Comment by ansibleguy76** [comment]
version 2.1.4 has a certificate ca bundle
