### ISSUE TITLE
Resource requirements and quotas

### ISSUE THREAD

**Issue by jakszk** [ansibleguy76/ansibleforms#6]
What are the resource requirements - min and recommended amounts of CPU, RAM required to maintain the application without any disturbances?
It would be also great to have some ability to set resource quotas during the deployment process (either via docker or kubernetes yaml files).
Thanks for your support!

**Comment by ansibleguy76** [comment]
I would recommend 512MB each (app and mysql).  A mysql can be tuned to consume more memory in the my.cnf file of course.  But default deployment is 512MB.  Cpu : a single core is sufficient.

I will adapt the docker-compose to have use those limits.

**Comment by jakszk** [comment]
Ok, Thanks for the information. In my case, I am going to apply resource limits to our kubernetes mysql and server deployments. There's no reference to limits in k8s files in your repo - for people knowing kubernetes, it is not a rocket science to modify the code, nonetheless, pls also consider adding (resource reservations and limits) it to k8s yaml files in the future.

**Comment by ansibleguy76** [comment]
It was a contributer who added the k8s files.  If you would be willing to contribute ?  You could fork and make a pull request ?  Or you could point me in the right direction.

**Comment by ansibleguy76** [comment]
the docker-compose is updated with limits (0.5 cpu and 512M ram)

**Comment by ansibleguy76** [comment]
added !
