### ISSUE TITLE
AWX connection - token should be invisible

### ISSUE THREAD

**Issue by jakszk** [ansibleguy76/ansibleforms#7]
Hello,

Currently a value in the token field under "AWX connection" page is fully visible. After pressing "Update Awx" button, it should become invisible not to expose it to any unauthorized users.

Thanks!

**Comment by ansibleguy76** [comment]
I have concidered that...  Would it be sufficient to make it a passwords field ?

**Comment by jakszk** [comment]
A password field + some encryption in the database should do the job I believe :)

**Comment by ansibleguy76** [comment]
in the database it's encrypted.
version 2.1.4 is being brewed... it will have your changes.  Also an AWX ca bundle !

**Comment by ansibleguy76** [comment]
v2.1.4 is online
