### ISSUE TITLE
AD-account

### ISSUE THREAD

**Issue by tonnyverberk** [ansibleguy76/ansibleforms#86]
**Is your feature request related to a problem? Please describe.**
Currently we are using AD-groups to login to 'ansible webforms'

**Describe the solution you'd like**
Is it possible to use AD-accounts, to grant only one specific user?

**Describe alternatives you've considered**
Local accounts, but we need the same password as the AD-account.

**Additional context**

**Comment by ansibleguy76** [comment]
building beta 4.0.11.
in roles, just as you add "groups", you can now also add "users".

users:
- local/admin
- ldap/myuser

connect back here once tested, I'll update the help too.

**Comment by ansibleguy76** [comment]
added in new version 4.0.11
