### ISSUE TITLE
Need file drag and drop fields for supporting file upload

### ISSUE THREAD

**Issue by nx2804** [ansibleguy76/ansibleforms#97]
Ansible forms should support a field for file drag and drop to upload a file like tar through ui, which supports the users to upload file to server without performing direct logins

**Comment by ansibleguy76** [comment]
can you give more information.  what would be the destination?  examples?

**Comment by nx2804** [comment]
![IMG_0330](https://github.com/ansibleguy76/ansibleforms/assets/142625328/bbd4227d-f48b-484d-bcb0-2ecbc244f525)
A kind of this image option.

through this the user will upload files to ansible nodes using forms without even logging into the server

**Comment by nx2804** [comment]
Is this possible through forms or even getting the field for location where the file should be uploaded with upload button would also be suffice

**Comment by ansibleguy76** [comment]
as an admin option in settings?  as a formfield?  and where would the file arrive?  in the docker image?

**Comment by ansibleguy76** [comment]
can you give an example of the purpose, just curious

**Comment by nachammaichidambaram** [comment]
It would be great if it can be one of forms field. 

I should be able to upload the file from my Local Machine to Ansible hosts through forms UI

Purpose:
We are having a scenario in production where only limited access will be permitted for operations team to logging in directly to the servers. If we can enable file upload through ui from operators laptop to ansible hosts through forms we can avoid direct ssh's to the servers. And on top of it playbooks will be  executed for extracting the files and configuring the servers

**Comment by ansibleguy76** [comment]
just for my info, do you use the docker image or are you deploying manually by compiling

**Comment by nx2804** [comment]
docker image

**Comment by ansibleguy76** [comment]
regarding how this would work.  It would basically have to upload the file(s) before the run button.  So first process the files, once they are uploaded, proceed with the playbook/template

**Comment by nachammaichidambaram** [comment]
Yep

**Comment by nachammaichidambaram** [comment]
For the first time user will login to the server and execute playbook a

From next time onwards user should perform operations through ui

Any such feasibility available in ansible forms for now

**Comment by ansibleguy76** [comment]
I was thinking to do the following :
- a new field type "file", that will upload the file to a temp location (prior to playbook start)
- the name of the field (extravar) will hold the "temp path" of the uploaded file => sent to your playbook.

You would have to do the following in your playbook :
- move the file to a location of your choice (you can handle that part using another field in the form, text or expression)

When the playbook is finished, I'll cleanup any temp files that were uploaded.

This will NOT work with AWX templates, Don't even know if you can send files to AWX.

Using this approach, you can choose the destination yourself (or let the operator decide).

PS : you can redirect the form to another form after success, making this a 2 step process.

**Comment by nx2804** [comment]
yeah this would be helpful.

**Comment by ansibleguy76** [comment]
i will try this week as a beta version

**Comment by nx2804** [comment]
Ok Thank you

**Comment by ansibleguy76** [comment]
a new beta is online.  can you test it.  Nothing special filters yet (no limit filesize yet, no extension filters, etc...).
a new uploads folder will be created under /data/ (tunable with env var) => docs website is up-to-date.  
you need to cleanup the files yourself.
the extravar will contain an object with info about the file (originalname, size, path, mimetype, ...)

keep me informed

**Comment by ansibleguy76** [comment]
Building new beta now, with progress bar.

**Comment by nachammaichidambaram** [comment]
Thanks let me check and get back to you

**Comment by ansibleguy76** [comment]
i am also adding regex and size limits

Op do 31 aug. 2023 om 10:23 schreef nachammaichidambaram <
***@***.***>

**Comment by ansibleguy76** [comment]
new beta added
- minSize
- maxSize
- regex (for file name)

common properties also available
- label, placeholder, icon, help

**Comment by nachammaichidambaram** [comment]
Is this available with ansible-forms docker-compose with latest changes?

**Comment by ansibleguy76** [comment]
beta for now
use :beta instead of :latest in docker compose

Op ma 18 sep. 2023 om 14:25 schreef nachammaichidambaram <
***@***.***>

**Comment by nx2804** [comment]
In docker image tag should I use beta instead of latest can you ping the
docs link for this

**Comment by ansibleguy76** [comment]
correct.  ansibleguy/ansibleforms:beta

thats all.

Op ma 18 sep. 2023 om 14:28 schreef nx2804 ***@***.***>

**Comment by nachammaichidambaram** [comment]
My docker containers are up for MySQL and ansible forms MySQL is listening
on port 3306 and web port is 8443


When I access the ui it gives me empty data response. Looks like the
communication between web and db is failing

Any idea how to fix this ?

**Comment by ansibleguy76** [comment]
and the :latest works fine?
did you checkout the installation procedure/youtube video. can you also make a new thread for this?

**Comment by nachammaichidambaram** [comment]
Latest also has the same problem

**Comment by ansibleguy76** [comment]
in that case there is something wrong with your setup.  read the installation instructions.  https://ansibleforms.com

**Comment by nachammaichidambaram** [comment]
I have managed to fix the issue. File upload was fine but it changes the
file name after uploading it also it would be great if you can provide an
option for entering the path in which the file should be uploaded

**Comment by nachammaichidambaram** [comment]
Also can we upload multiple files at a time?

**Comment by ansibleguy76** [comment]
of course

**Comment by nachammaichidambaram** [comment]
How do I overcome the file name being modified during upload issue

**Comment by ansibleguy76** [comment]
I create a temp name on purpose to avoid doubles.  However, the field exports an object containing the original name and the tempname.  The idea is to move + rename the file to its final destination.  Since the form just uploads but doesn't perform any cleanup.

**Comment by nachammaichidambaram** [comment]
In my playbook I can refer uploads/actual filename and use is it?

**Comment by nx2804** [comment]
I can upload only one file at a time it is not allowing multiple files to
be uploaded

**Comment by ansibleguy76** [comment]
Did you create 2 "filetype" fields ?

**Comment by ansibleguy76** [comment]
Every field allows 1 file.  Do you need multiple files per field ?  If I allow multiple, it's a potential issue, cause 1 regex is harder to double check multiple files.  Therefor I chose for 1 file per field, but you can add multiple file-fields.  The uploads happen in parallel.

**Comment by nx2804** [comment]
ok thanks will check and how can i pass the inventory for ansible
dynamically with group names or any default path where you search for
inventory file like how you have playbooks/play.yml

**Comment by ansibleguy76** [comment]
can you please open a thread for different topics.  this thread is about uploading files. 

also check out de documentation.

**Comment by ansibleguy76** [comment]
I assume this can be closed ?  Reopen if needed.
