### ISSUE TITLE
instructions or environment variable for passing inventory file path

### ISSUE THREAD

**Issue by nx2804** [ansibleguy76/ansibleforms#98]
in docs there is not elaborated examples provided for inventories

**Comment by nx2804** [comment]
i tried already provided inventory formfield  
    categories:
      - Ansible
    playbook: test.yaml
    inventory: inventory.yaml
    
also i tried passing dynamic inventory with the help of fields

fields:
- type: __inventory__
  name: inventory
  this is failing with validation errors

**Comment by ansibleguy76** [comment]
there is no field type inventory, use text, expression, ... whatever fits your needs to fill the value of the inventory name.
but name the field "__inventory__" => not "inventory".

example :

```
type: expression
runLocal: true
expression: "'bla.yaml'"
hide: true
name: __inventory__
```

**Comment by ansibleguy76** [comment]
If you want it operator driven, use a text field, or use enum field with dropdown... many options

**Comment by nx2804** [comment]
where should be the inventory file located? under data/inventory path?

**Comment by ansibleguy76** [comment]
data/playbooks

that is the "ansible" path used.

**Comment by ansibleguy76** [comment]
data is a parent for many things, database, certificates, forms.  playbooks is one of the them and hosts your
 ansible files

**Comment by nx2804** [comment]
what if the remote hosts requires ssh username and password or private key
file how can i pass that

**Comment by nx2804** [comment]
ansible-playbook playbook.yaml -u <username> --ask-pass < password>

**Comment by ansibleguy76** [comment]
you should place these in the inventory, no ?

**Comment by nx2804** [comment]
In inventory file if I pass ansible_ssh_pass with value it got failed with
error as sshpass should be installed the docker image

And for key file how to pass in forms and where the key should be placed(
which location) under data

**Comment by nx2804** [comment]
any response on this

**Comment by ansibleguy76** [comment]
can you please give detailed steps on what you try, how it works outside docker and how it fails inside docker. so i can reproduce.

**Comment by nx2804** [comment]
I was trying to connect to a host machine from container using ssh

under data/playbook/test.yaml
- name: test
  hosts: all
  tasks:
  - name: ansibleforms execution
    shell: rpm -i <rpmfilename>


under data/playbook/inventory.yaml
all:
   hosts:
       <ipaddress>
   vars:
      ansible_ssh_password: <password>
      ansible_user: <username>


i tried setting the password using ansible_ssh_pass / ansible_password
/ansible_ssh_password, When it tries to perform ssh from container to
target host it fails with sshpass should be installed error

Note: I have already installed sshpass package in my hostmachine. So in
container it is looking for sshpass

**Comment by nx2804** [comment]
are you able to replicate it ?

**Comment by nx2804** [comment]
Hello any response on this?

**Comment by ansibleguy76** [comment]
Sorry.. been busy.. I'll pick it up asap !

**Comment by nx2804** [comment]
I have created on more question is it possible to create variable from ui
like survey variables in awx

**Comment by ansibleguy76** [comment]
I have just deployed a new beta I would like you to try where I installed sshpass in the docker image.

**Comment by nx2804** [comment]
Ok let me try

**Comment by ansibleguy76** [comment]
in the newest latest release, with the sshpass, I don't see any issues. I tried inventories with ansible_ssh_pass and it all works fine.  I did have to add the ip's to the known hosts (possible in settings) (or disable the key checking)
