### ISSUE TITLE
Feature for supporting dynamic variables through ui like Survey in AWX

### ISSUE THREAD

**Issue by nx2804** [ansibleguy76/ansibleforms#99]
User should be able to add the new variable with either text/password through UI like how surveys work in AWX
Kindly provide suggestion if solution already exists

**Comment by ansibleguy76** [comment]
Isn't that the whole idea of ansible forms ?  Passing variables ?  can you please explain further ?

**Comment by nx2804** [comment]
In ansible forms for each and every field we need to update the code for
adding new field I would like to do it from ui


Say for example awx supports dynamic survey variables which can be created
from ui

**Comment by ansibleguy76** [comment]
I'm a bit surprised, since I started AF because of the poor surveys in AWX.  But you are right,  fields can be hidden/shown but you can't just create new fields on the fly.   And honestly I don't really like that idea.  Creating forms is a lot about control and validation.  Just out of curiosity, can you give a situation where this would be needed ?

**Comment by ansibleguy76** [comment]
Re-reading, maybe I misunderstood the question.  Are you asking for a mechanisme where you can generate new fields from within a form.  Or are you asking for a graphical designer to design forms.

**Comment by nx2804** [comment]
Generating new fields like selecting add button and field type is text
/password or drop-down giving its name from ui and default value

**Comment by ansibleguy76** [comment]
I don't see the value in implementing this in AF.  AF was meant to collect a certain set of data that can be controlled by the form architect and not allow to freewheel.  Can you give me a business case where this would interesting ?

**Comment by nx2804** [comment]
Hi

The same controller usecase they would need a single ui to support upload
files and deploy/rollback app without even logging into the server

**Comment by nx2804** [comment]
They should be able to override default variable values through ui by
adding a field

**Comment by nx2804** [comment]
Not like that we have three teams one from internal ops who find the
solution and implement with flexibility for developer  to extend it through
ui and the final version will be consumed by operator in production

**Comment by nx2804** [comment]
Maybe I will try with validation and see how it helps

**Comment by ansibleguy76** [comment]
Hi, is this now ok ?

**Comment by nx2804** [comment]
this is not like survey it expects the static code change for including a field

**Comment by ansibleguy76** [comment]
correct, the form must be designed by an architect.  still i don't understand why you would want this. your playbook is static too.  so you know up front the required variables.  so you can design the form upfront too.
